# Generated by Django 5.0.4 on 2024-04-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotManager', '0002_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticdata',
            name='leverage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='staticdata',
            name='volume',
            field=models.FloatField(),
        ),
    ]
