# Generated by Django 5.0.4 on 2024-04-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BotManager', '0003_alter_staticdata_leverage_alter_staticdata_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsignals',
            name='coinpair',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botsignals',
            name='side',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
